"""moving notes to details

Revision ID: ba1ee06591f6
Revises: 102c5739d625
Create Date: 2022-04-20 02:46:06.813326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1ee06591f6'
down_revision = '102c5739d625'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cchannel_order_detail_logs', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('cchannel_order_details', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('cchannel_order_logs', 'notes')
    op.drop_column('cchannel_orders', 'notes')
    op.add_column('ds_order_detail_logs', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('ds_order_details', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('ds_order_logs', 'notes')
    op.drop_column('ds_orders', 'notes')
    op.add_column('roof_order_detail_logs', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('roof_order_details', sa.Column('notes', sa.String(), nullable=True))
    op.drop_column('roof_order_logs', 'notes')
    op.drop_column('roof_orders', 'notes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roof_orders', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('roof_order_logs', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('roof_order_details', 'notes')
    op.drop_column('roof_order_detail_logs', 'notes')
    op.add_column('ds_orders', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ds_order_logs', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ds_order_details', 'notes')
    op.drop_column('ds_order_detail_logs', 'notes')
    op.add_column('cchannel_orders', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cchannel_order_logs', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('cchannel_order_details', 'notes')
    op.drop_column('cchannel_order_detail_logs', 'notes')
    # ### end Alembic commands ###
