"""new db design

Revision ID: cb5c579bf2b3
Revises: 
Create Date: 2022-05-01 03:12:06.486925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb5c579bf2b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('transcation_type', sa.Enum('insert', 'update', 'delete', name='transtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', name='gender'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('manager_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('admin', 'issuer', 'listener', name='managertype'), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('transcation_type', sa.Enum('insert', 'update', 'delete', name='transtype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('admin', 'issuer', 'listener', name='managertype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('transcations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_type', sa.Enum('ds', 'c_purlin', 'u_beam', 'i_beam', 'c_channel', 'hollow', 'plain', 'roof', name='product'), nullable=False),
    sa.Column('transcation_type', sa.Enum('insert', 'update', 'delete', name='transtype'), nullable=False),
    sa.Column('production_stage', sa.Enum('pending', 'producing', 'done', name='productionstage'), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cchannel_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ds_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roof_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cchannel_order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cchannel_order_id', sa.Integer(), nullable=False),
    sa.Column('channel_height', sa.FLOAT(precision=2), nullable=False),
    sa.Column('channel_width', sa.FLOAT(precision=2), nullable=False),
    sa.Column('holes', sa.String(), nullable=True),
    sa.Column('length_per_sheet', sa.FLOAT(precision=2), nullable=False),
    sa.Column('no_of_sheets', sa.Integer(), nullable=False),
    sa.Column('total_length', sa.FLOAT(precision=4), nullable=False),
    sa.Column('thickness', sa.FLOAT(precision=2), nullable=False),
    sa.Column('zinc_grade', sa.Integer(), nullable=False),
    sa.Column('pick_up_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('production_stage', sa.Enum('pending', 'producing', 'done', name='productionstage'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cchannel_order_id'], ['cchannel_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ds_order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ds_order_id', sa.Integer(), nullable=False),
    sa.Column('depth', sa.FLOAT(precision=1), nullable=False),
    sa.Column('length_per_sheet', sa.FLOAT(precision=2), nullable=False),
    sa.Column('no_of_sheets', sa.Integer(), nullable=False),
    sa.Column('total_length', sa.FLOAT(precision=4), nullable=False),
    sa.Column('thickness', sa.FLOAT(precision=2), nullable=False),
    sa.Column('zinc_grade', sa.Integer(), nullable=False),
    sa.Column('pick_up_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('production_stage', sa.Enum('pending', 'producing', 'done', name='productionstage'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ds_order_id'], ['ds_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roof_order_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roof_order_id', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.Enum('taiwan', 'china', 'vietnam', name='colorplainmanufacturer'), nullable=False),
    sa.Column('length_per_sheet', sa.FLOAT(precision=2), nullable=False),
    sa.Column('no_of_sheets', sa.Integer(), nullable=False),
    sa.Column('total_length', sa.FLOAT(precision=4), nullable=False),
    sa.Column('thickness', sa.FLOAT(precision=2), nullable=False),
    sa.Column('pick_up_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('production_stage', sa.Enum('pending', 'producing', 'done', name='productionstage'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['roof_order_id'], ['roof_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roof_order_details')
    op.drop_table('ds_order_details')
    op.drop_table('cchannel_order_details')
    op.drop_table('roof_orders')
    op.drop_table('ds_orders')
    op.drop_table('cchannel_orders')
    op.drop_table('transcations')
    op.drop_table('managers')
    op.drop_table('manager_logs')
    op.drop_table('customers')
    op.drop_table('customer_logs')
    # ### end Alembic commands ###
